-- SILENTRA Ticket <-> Dashboard shared contract
-- Safe to run after the existing servers/tickets tables exist.

alter table public.servers
  add column if not exists admin_role_id bigint,
  add column if not exists ticket_role_id bigint,
  add column if not exists ticket_language text,
  add column if not exists updated_at timestamptz default now();

alter table public.tickets
  add column if not exists priority text default 'normal',
  add column if not exists assigned_to bigint,
  add column if not exists claimed_at timestamptz,
  add column if not exists last_activity_at timestamptz,
  add column if not exists closed_by bigint,
  add column if not exists resolution_note text,
  add column if not exists updated_at timestamptz default now();

create table if not exists public.ticket_messages (
  id bigint generated by default as identity primary key,
  guild_id bigint not null,
  channel_id bigint not null,
  message_id bigint not null unique,
  author_id bigint not null,
  author_name text,
  content text,
  created_at timestamptz not null default now(),
  edited_at timestamptz,
  attachment_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists ticket_messages_channel_created_idx
  on public.ticket_messages (guild_id, channel_id, created_at desc);

create table if not exists public.ticket_events (
  id bigint generated by default as identity primary key,
  guild_id bigint not null,
  channel_id bigint not null,
  event_type text not null,
  actor_id bigint,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  error text,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists ticket_events_pending_idx
  on public.ticket_events (status, created_at)
  where status = 'pending';

create index if not exists ticket_events_ticket_idx
  on public.ticket_events (guild_id, channel_id, created_at desc);

create or replace function public.touch_ticket_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tickets_touch_updated_at on public.tickets;
create trigger tickets_touch_updated_at
before update on public.tickets
for each row execute function public.touch_ticket_updated_at();

drop trigger if exists servers_touch_updated_at on public.servers;
create trigger servers_touch_updated_at
before update on public.servers
for each row execute function public.touch_ticket_updated_at();

-- Enable realtime for dashboard live updates when the tables are present in the publication.
do $$
begin
  begin
    alter publication supabase_realtime add table public.tickets;
  exception
    when duplicate_object or undefined_object then null;
  end;

  begin
    alter publication supabase_realtime add table public.ticket_messages;
  exception
    when duplicate_object or undefined_object then null;
  end;

  begin
    alter publication supabase_realtime add table public.ticket_events;
  exception
    when duplicate_object or undefined_object then null;
  end;
end;
$$;

notify pgrst, 'reload schema';
